# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.2
mod_id = ioticblocks
maven_group = gay.object.ioticblocks
archives_name = ioticblocks
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1
yarn_mappings = 1.21.1+build.1#remove
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.11.10

# Dependencies
architectury_api_version = 13.0.8
fabric_loader_version = 0.19.3
fabric_api_version = 0.116.12+1.21.1
neoforge_version = 21.1.215
yarn_mappings_patch_neoforge_version = 1.21+build.6
forgeconfigapiport_version=21.1.3
patchouli_version = 92
paucal_version = 0.7.1-pre-27
hexcasting_version = 0.12.0-devel-pre-36
inline_version = 1.2.2
accessories_version= 1.1.0-beta.16

#neoForge only
kotlin_neoforge = 5.10.0
caelus_version = 7.0.1

#fabric only
flk_version=1.13.9+kotlin.2.3.10
cc_version=6.1.3
cloth_config_version=15.0.140
mod_menu_version=11.0.4

# enable dokka gradle plugin v2
# https://kotlinlang.org/docs/dokka-migration.html
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true